package com.wildcard.buddycards.client.renderer;

import com.mojang.blaze3d.matrix.MatrixStack;
import com.wildcard.buddycards.blocks.CardDisplayBlock;
import com.wildcard.buddycards.blocks.tiles.CardDisplayTile;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.IRenderTypeBuffer;
import net.minecraft.client.renderer.model.IBakedModel;
import net.minecraft.client.renderer.model.ItemCameraTransforms;
import net.minecraft.client.renderer.tileentity.TileEntityRenderer;
import net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher;
import net.minecraft.item.ItemStack;
import net.minecraft.util.math.vector.Vector3f;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class CardDisplayTileRenderer extends TileEntityRenderer<CardDisplayTile> {
    public CardDisplayTileRenderer(TileEntityRendererDispatcher rendererDispatcherIn) {
        super(rendererDispatcherIn);
    }

    @Override
    public void render(CardDisplayTile tileEntityIn, float partialTicks, MatrixStack matrixStackIn, IRenderTypeBuffer bufferIn, int combinedLightIn, int combinedOverlayIn) {
        switch(tileEntityIn.getBlockState().getValue(CardDisplayBlock.DIR)) {
            case NORTH: {
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.1875, 0.75, 0.125);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(180));
                ItemStack itemstack = tileEntityIn.getCardInSlot(1);
                IBakedModel ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.5, 0.75, 0.13);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(180));
                itemstack = tileEntityIn.getCardInSlot(2);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.8125, 0.75, 0.125);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(180));
                itemstack = tileEntityIn.getCardInSlot(3);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.1875, 0.25, 0.125);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(180));
                itemstack = tileEntityIn.getCardInSlot(4);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.5, 0.25, 0.13);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(180));
                itemstack = tileEntityIn.getCardInSlot(5);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.8125, 0.25, 0.125);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(180));
                itemstack = tileEntityIn.getCardInSlot(6);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                break;
            }
            case EAST: {
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.875, 0.75, 0.1875);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(90));
                ItemStack itemstack = tileEntityIn.getCardInSlot(1);
                IBakedModel ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.87, 0.75, 0.5);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(90));
                itemstack = tileEntityIn.getCardInSlot(2);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.875, 0.75, 0.8125);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(90));
                itemstack = tileEntityIn.getCardInSlot(3);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.875, 0.25, 0.1875);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(90));
                itemstack = tileEntityIn.getCardInSlot(4);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.87, 0.25, 0.5);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(90));
                itemstack = tileEntityIn.getCardInSlot(5);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.875, 0.25, 0.8125);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(90));
                itemstack = tileEntityIn.getCardInSlot(6);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                break;
            }
            case SOUTH: {
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.8125, 0.75, 0.875);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                ItemStack itemstack = tileEntityIn.getCardInSlot(1);
                IBakedModel ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.5, 0.75, 0.87);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                itemstack = tileEntityIn.getCardInSlot(2);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.1875, 0.75, 0.875);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                itemstack = tileEntityIn.getCardInSlot(3);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.8125, 0.25, 0.875);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                itemstack = tileEntityIn.getCardInSlot(4);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.5, 0.25, 0.87);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                itemstack = tileEntityIn.getCardInSlot(5);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.1875, 0.25, 0.875);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                itemstack = tileEntityIn.getCardInSlot(6);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                break;
            }
            case WEST: {
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.125, 0.75, 0.8125);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(270));
                ItemStack itemstack = tileEntityIn.getCardInSlot(1);
                IBakedModel ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.13, 0.75, 0.5);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(270));
                itemstack = tileEntityIn.getCardInSlot(2);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.125, 0.75, 0.1875);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(270));
                itemstack = tileEntityIn.getCardInSlot(3);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.125, 0.25, 0.8125);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(270));
                itemstack = tileEntityIn.getCardInSlot(4);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.13, 0.25, 0.5);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(270));
                itemstack = tileEntityIn.getCardInSlot(5);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                matrixStackIn.pushPose();
                matrixStackIn.translate(0.125, 0.25, 0.1875);
                matrixStackIn.scale(0.5f, 0.5f, 0.5f);
                matrixStackIn.mulPose(Vector3f.YP.rotationDegrees(270));
                itemstack = tileEntityIn.getCardInSlot(6);
                ibakedmodel = Minecraft.getInstance().getItemRenderer().getModel(itemstack, tileEntityIn.getLevel(), null);
                Minecraft.getInstance().getItemRenderer().render(itemstack, ItemCameraTransforms.TransformType.FIXED, true, matrixStackIn, bufferIn, combinedLightIn, combinedOverlayIn, ibakedmodel);
                matrixStackIn.popPose();
                break;
            }
        }
    }
}
